name: Publish packages to public repositories

on:
  workflow_call:
    inputs:
      artifactName:
        required: true
        type: string
        description: "The github artifact holding the wheel file which will be published"
  workflow_dispatch:
    inputs:
      release:
        required: true
        type: string
        description: "The github release which will be published"

jobs:
  publish-brew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      # Download either via release or provided artifact
      - name: Download release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: gh release download ${{ inputs.release }} --pattern "*.whl" --dir dist

      - name: Download artifact
        if: ${{ github.event_name == 'workflow_call' }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifactName }}
          path: dist

      - name: Update homebrew formula
        run: scripts/update-brew-formula.sh "dist/helloworld-*-py3-none-any.whl" "daniel-makerx/homebrew-tap"
        env:
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
